#ifndef _GLOBALS_H
#define _GLOBALS_H

enum class Errors_e
{
	NO_ERROR,

	AUDIO_MANAGER_NOT_INITIALIZED,
	AUDIO_MANAGER_NO_USB_CARDS_FOUND,
	AUDIO_MANAGER_CANT_OPEN_PCM_DEVICE,
	AUDIO_MANAGER_CARD_CONFIG_FAILURE,
	AUDIO_MANAGER_RECORDER_NOT_READY
};

#endif
