#ifndef _GLOBALS_H
#define _GLOBALS_H

enum class Errors_e
{
	NO_ERROR,
	
	AUDIO_CONFIG_CANT_OPEN_PCM_DEVICE,
	AUDIO_CONFIG_ERROR_ALLOCATING_PARAM_HW,
	AUDIO_CONFIG_ERROR_INITIALIZING_PARAM,
	AUDIO_CONFIG_ERROR_SETTING_ACCESS_MODE,
	AUDIO_CONFIG_ERROR_SETTING_AUDIO_FORMAT,
	AUDIO_CONFIG_ERROR_SETTING_SAMPLE_RATE,
	AUDIO_CONFIG_ERROR_SETTING_NUMBER_OF_CHANNELS,
	AUDIO_CONFIG_ERROR_APPLYING_HW_PARAMS,
	AUDIO_CONFIG_ERROR_PREPARING_INTERFACE,

	AUDIO_MANAGER_NOT_INITIALIZED,
	AUDIO_MANAGER_NO_USB_CARDS_FOUND
};

#endif
